name: Production deploy
on:
  push:
    tags:
      - v**
jobs:
  deploy:
    name: Deploy to production server
    runs-on: [self-hosted, sport]
    environment:
      name: production
      url: https://sport.innopolis.university
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.REPOSITORY_PATH }}/deploy
            git reset --hard
            git fetch
            git checkout ${{ github.ref_name }}
            git pull
            python3 ${{ secrets.BACKUP_SCRIPT }}
            docker compose -f docker-compose.prod.yaml pull
            docker compose -f docker-compose.prod.yaml build --pull
            docker compose -f docker-compose.prod.yaml down
            docker compose -f docker-compose.prod.yaml up -d
            python3 ${{ secrets.BACKUP_SCRIPT }}
