name: Staging deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Tests"]
    branches: [main]
    types:
      - completed
jobs:
  deploy:
    name: Deploy to staging server
    runs-on: [self-hosted, sport]
    environment:
      name: development
      url: https://stage.sport.innopolis.university
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.REPOSITORY_PATH }}/deploy
            git reset --hard
            git fetch
            git checkout ${{ github.ref_name }}
            git pull
            docker compose -f docker-compose.prod.yaml pull
            docker compose -f docker-compose.prod.yaml build --pull
            docker compose -f docker-compose.prod.yaml down
            docker compose -f docker-compose.prod.yaml up -d
